export const initialState = {
  isLoggedIn: false,
  disableLoginButton: false,
  adminAccessToken: "",
  userAccessToken: "",
  user:{},
  isCheckingToken: true,
  userDetails: {},
  adminDetails: {},
  permissions: {},
  allServices:[],
  services:[],
  kitchenData:[],
  kicthenCategories:[],
  allPackages:[],
  contactUsDetails:{},
  cartItems:[],
  type:"",
};
